# Generated by Django 4.2.1 on 2023-05-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computadoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo_disco', models.CharField(choices=[('M2', 'M.2'), ('SSD', 'SSD'), ('HDD', 'HDD')], max_length=3)),
                ('capacidad_disco', models.CharField(choices=[('32', '32gb'), ('64', '64gb'), ('128', '128gb'), ('256', '256gb'), ('512', '512gb'), ('1024', '1024gb')], max_length=4)),
                ('tipo_ram', models.CharField(choices=[('DDR', 'DDR'), ('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=4)),
                ('memoria1_ram', models.CharField(choices=[('4', '4gb'), ('8', '8gb'), ('16', '16gb'), ('32', '32gb'), ('64', '64gb')], max_length=2)),
                ('memoria2_ram', models.CharField(choices=[('4', '4gb'), ('8', '8gb'), ('16', '16gb'), ('32', '32gb'), ('64', '64gb')], max_length=2)),
                ('procesador', models.CharField(choices=[('I3', 'i3'), ('I5', 'i5'), ('I7', 'i7'), ('C2D', 'Core2Duo'), ('ADM', 'ADM'), ('OTROS', 'OTROS...')], max_length=7)),
                ('actualizada', models.BooleanField(choices=[(True, 'Actualizada'), (False, 'No actualizada')], default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_nomina', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('departamento', models.CharField(choices=[('S', 'Sistemas'), ('P', 'Presidencia')], max_length=1)),
                ('cargo', models.CharField(choices=[('J', 'Jefe'), ('A', 'Administrador')], max_length=1)),
            ],
        ),
    ]
