# Generated by Django 4.2.1 on 2023-05-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAEE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computadoras',
            name='serial',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='cod_nomina',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
