# Generated by Django 4.2.1 on 2023-05-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAEE', '0003_asignacioncomputadora'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsignacionComputadora',
        ),
    ]
