# Generated by Django 4.2 on 2023-05-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RAEE', '0004_delete_asignacioncomputadora'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadoras',
            name='empleado_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_asignados', to='RAEE.empleados'),
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='RAEE.computadoras')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='RAEE.empleados')),
            ],
        ),
    ]
