# Generated by Django 4.2 on 2023-05-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAEE', '0005_computadoras_empleado_asignado_asignacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computadoras',
            name='empleado_asignado',
        ),
        migrations.DeleteModel(
            name='Asignacion',
        ),
    ]
