# Generated by Django 4.2 on 2023-05-25 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RAEE', '0008_remove_computadoras_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computadoras',
            name='empleado_asignado',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RAEE.empleados'),
        ),
    ]
