# Generated by Django 4.2.1 on 2023-05-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAEE', '0011_alter_computadoras_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computadoras',
            name='actualizada',
            field=models.BooleanField(choices=[('SI', 'Actualizada'), ('NO', 'No actualizada')], default=False),
        ),
    ]
