# Generated by Django 4.2.1 on 2023-05-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAEE', '0012_alter_computadoras_actualizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computadoras',
            name='actualizada',
            field=models.BooleanField(choices=[('SI', 'SI'), ('NO', 'NO')], default=False),
        ),
    ]
