# Generated by Django 4.2.1 on 2023-05-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAEE', '0013_alter_computadoras_actualizada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computadoras',
            name='estado',
        ),
        migrations.AddField(
            model_name='computadoras',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
    ]
