# Generated by Django 4.2.1 on 2023-05-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAEE', '0014_remove_computadoras_estado_computadoras_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computadoras',
            name='actualizada',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2),
        ),
    ]
