# Generated by Django 4.2.1 on 2023-05-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAEE', '0015_alter_computadoras_actualizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computadoras',
            name='asignado',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2),
        ),
    ]
