# Generated by Django 4.2.1 on 2023-05-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAEE', '0016_alter_computadoras_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computadoras',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
    ]
