# Generated by Django 4.2.1 on 2023-05-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAEE', '0017_alter_computadoras_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computadoras',
            name='fecha_asignacion',
            field=models.DateField(null=True),
        ),
    ]
